/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_maczkowiak_version_graphique;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author lukha
 */
public class FenetreVictoire extends javax.swing.JFrame {

    /**
     * Creates new form FenetreVictoire
     */
    public FenetreVictoire() {
        initComponents();
        getContentPane().setBackground(new Color(54,55,53));
        vic_lab.setForeground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vic_lab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vic_lab.setFont(new java.awt.Font("Agency FB", 3, 64)); // NOI18N
        vic_lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vic_lab.setText("YOU WON");
        getContentPane().add(vic_lab, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel vic_lab;
    // End of variables declaration//GEN-END:variables
}
