/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_maczkowiak_version_graphique;
import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import static lightoff_maczkowiak_version_graphique.Partie.rand;
/**
 *
 * @author lukha
 */
public class Menu extends javax.swing.JFrame {
    private int nbCoups;
    private int difficulty = 0;
    int[] coord = new int[2];
    private fenetreDeJeu Mainframe;
    /**
     * Creates new form Menu
     */
    public Menu(fenetreDeJeu main) {
        Mainframe = main;
        initComponents();
        Panel_selecsize.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_difficultés = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Difficile = new javax.swing.JButton();
        Facile = new javax.swing.JButton();
        Normal = new javax.swing.JButton();
        Panel_selecsize = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        slide_select = new javax.swing.JSlider();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneau_difficultés.setBackground(new java.awt.Color(102, 102, 102));
        panneau_difficultés.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panneau_difficultés.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECTIONNER UNE DIFFICULTE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panneau_difficultés.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        Difficile.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        Difficile.setText("DIFFICILE");
        Difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifficileActionPerformed(evt);
            }
        });
        panneau_difficultés.add(Difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        Facile.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        Facile.setText("FACILE");
        Facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacileActionPerformed(evt);
            }
        });
        panneau_difficultés.add(Facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        Normal.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        Normal.setText("NORMAL");
        Normal.setAlignmentY(0.0F);
        Normal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });
        panneau_difficultés.add(Normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        Panel_selecsize.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("SELECTIONNER LA TAILLE DE LA GRILLE SOUHAITEE");

        slide_select.setBackground(new java.awt.Color(51, 51, 51));
        slide_select.setForeground(new java.awt.Color(153, 153, 153));

        Valider.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        Valider.setText("VALIDER");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_selecsizeLayout = new javax.swing.GroupLayout(Panel_selecsize);
        Panel_selecsize.setLayout(Panel_selecsizeLayout);
        Panel_selecsizeLayout.setHorizontalGroup(
            Panel_selecsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_selecsizeLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_selecsizeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_selecsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_selecsizeLayout.createSequentialGroup()
                        .addComponent(Valider)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_selecsizeLayout.createSequentialGroup()
                        .addComponent(slide_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        Panel_selecsizeLayout.setVerticalGroup(
            Panel_selecsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_selecsizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slide_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Valider)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(panneau_difficultés, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(Panel_selecsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneau_difficultés, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Panel_selecsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DifficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifficileActionPerformed
        difficulty = 3;
        nbCoups = 40;
        while (coord[0] == coord[1]) {
            coord[0] = rand.nextInt(7, 10);
            coord[1] = rand.nextInt(7, 10);
        }
        DebutDuJeu();
    }//GEN-LAST:event_DifficileActionPerformed

    private void FacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacileActionPerformed
        difficulty = 1;
        nbCoups = 0;
        Panel_selecsize.setVisible(true);
        Selection_Grille(3,5);
    }//GEN-LAST:event_FacileActionPerformed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        difficulty = 2;
        nbCoups = 0;
        Panel_selecsize.setVisible(true);
        Selection_Grille(5, 7);
    }//GEN-LAST:event_NormalActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        DebutDuJeu();
    }//GEN-LAST:event_ValiderActionPerformed
    
    private void Selection_Grille(int min, int max){
        slide_select = new JSlider(JSlider.HORIZONTAL, min, max, (max+min)/2);
        slide_select.setMajorTickSpacing(20); // Major tick every 20 units
        slide_select.setMinorTickSpacing(5); // Minor tick every 5 units
        slide_select.setPaintTicks(true);
        slide_select.setSnapToTicks(true);
        slide_select.setPaintLabels(true);
        /*// Create a label table to specify custom labels
            Hashtable<Integer, JLabel> labelTable = new Hashtable<>();
            for (int i=min;i<max+1;i++){
                labelTable.put(i, new JLabel(i+""));
            }
            
            
        slide_select.setLabelTable(labelTable);*/
        slide_select.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    JSlider source = (JSlider) e.getSource();
                    int value = source.getValue();
                    coord[0]=value;
                    coord[1]=value;  
                }
            });
    }
    private void DebutDuJeu(){
        Mainframe.UpdateValues(difficulty, nbCoups, coord);
        Mainframe.setVisible(true);
        Mainframe.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Difficile;
    private javax.swing.JButton Facile;
    private javax.swing.JButton Normal;
    private javax.swing.JPanel Panel_selecsize;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panneau_difficultés;
    private javax.swing.JSlider slide_select;
    // End of variables declaration//GEN-END:variables
}
